# Azure 開発環境用の設定
version: '3.8'

services:
  web:
    build: .
    image: repti_track:latest
    command: bundle exec rails server -e production -b '0.0.0.0'
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# # ローカル
# version: '3.8'

# services:
#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_DB: reptitrack
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   web:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/rails
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://myuser:password@db:5432/myapp_development
#       RAILS_ENV: development

# volumes:
#   postgres_data: