version: '3.8'

services:
  db:
    image: postgres
    platform: linux/arm64/v8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"  # ポートを5432から5433に変更

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'  # コマンドを修正
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/myapp_development # ポート番号も変更
      RAILS_ENV: development

volumes:
  postgres_data:

# version: '3.8'

# services:
#   web:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/rails
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: postgres://yukina21053:jbus0911@repti-track-database-1.ch0eu8wewati.ap-northeast-1.rds.amazonaws.com:5432/myapp_development
#       RAILS_ENV: production  # 環境を本番用に変更

# volumes:
#   postgres_data: