# AzureのPostgreSQLの設定
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  # Azure Database for PostgreSQLを開発環境でも使用する場合
  database: <%= ENV['DATABASE_NAME'] %>  # 環境変数から取得
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

test:
  <<: *default
  database: myapp_test  # テスト用データベース名

production:
  <<: *default
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>  # 環境変数から取得
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>


# # ローカル開発環境用の設定
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: myuser  # ローカルのPostgreSQLのユーザー名
#   password: password  # ローカルのPostgreSQLのパスワード
#   host: localhost
#   port: 5432
#   database: reptitrack  # データベース名

# development:
#   <<: *default
#   database: myapp_development  # 開発用データベース名

# test:
#   <<: *default
#   database: myapp_test  # テスト用データベース名

# production:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   url: <%= ENV['DATABASE_URL'] %>   # 本番用データベースURL