# # ローカル開発環境用の設定
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: myuser  # ローカルのPostgreSQLのユーザー名
#   password: password  # ローカルのPostgreSQLのパスワード
#   host: db
#   port: 5432
#   database: reptitrack  # データベース名

# development:
#   <<: *default
#   database: myapp_development  # 開発用データベース名

# test:
#   <<: *default
#   database: myapp_test  # テスト用データベース名

# production:
#   <<: *default
#   database: myapp_production  # 本番用データベース名

# Azure Database for PostgreSQL使用の場合
# ローカル開発環境用の設定
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
